python convert_generic_to_toyota_structure.py -r D:\output-datasets\onroad-3-toyota
python convert_generic_to_toyota_structure.py -r D:\output-datasets\onroad-5-toyota
python convert_generic_to_toyota_structure.py -r D:\output-datasets\onroad-7-toyota
python convert_generic_to_toyota_structure.py -r D:\output-datasets\onroad-10-toyota
python convert_generic_to_toyota_structure.py -r D:\output-datasets\onroad-11-toyota
python convert_generic_to_toyota_structure.py -r Z:\onroad-3-toyota
python convert_generic_to_toyota_structure.py -r Z:\onroad-5-toyota
python convert_generic_to_toyota_structure.py -r Z:\onroad-7-toyota
python convert_generic_to_toyota_structure.py -r Z:\onroad-10-toyota
python convert_generic_to_toyota_structure.py -r Z:\onroad-11-toyota
